/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTelefoniaRouteImport } from './routes/_authenticated/telefonia'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedLegalCasesRouteImport } from './routes/_authenticated/legal-cases'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCriativosRouteImport } from './routes/_authenticated/criativos'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWebhooksUazapiRouteImport } from './routes/api/public/webhooks/uazapi'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTelefoniaRoute = AuthenticatedTelefoniaRouteImport.update({
  id: '/telefonia',
  path: '/telefonia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegalCasesRoute = AuthenticatedLegalCasesRouteImport.update({
  id: '/legal-cases',
  path: '/legal-cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriativosRoute = AuthenticatedCriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksUazapiRoute = ApiPublicWebhooksUazapiRouteImport.update({
  id: '/api/public/webhooks/uazapi',
  path: '/api/public/webhooks/uazapi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/criativos': typeof AuthenticatedCriativosRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/legal-cases': typeof AuthenticatedLegalCasesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/telefonia': typeof AuthenticatedTelefoniaRoute
  '/api/public/webhooks/uazapi': typeof ApiPublicWebhooksUazapiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agentes': typeof AuthenticatedAgentesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/criativos': typeof AuthenticatedCriativosRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/legal-cases': typeof AuthenticatedLegalCasesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/telefonia': typeof AuthenticatedTelefoniaRoute
  '/api/public/webhooks/uazapi': typeof ApiPublicWebhooksUazapiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/criativos': typeof AuthenticatedCriativosRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/legal-cases': typeof AuthenticatedLegalCasesRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/telefonia': typeof AuthenticatedTelefoniaRoute
  '/api/public/webhooks/uazapi': typeof ApiPublicWebhooksUazapiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agentes'
    | '/chat'
    | '/comercial'
    | '/configuracoes'
    | '/contatos'
    | '/criativos'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/legal-cases'
    | '/plans'
    | '/telefonia'
    | '/api/public/webhooks/uazapi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agentes'
    | '/chat'
    | '/comercial'
    | '/configuracoes'
    | '/contatos'
    | '/criativos'
    | '/crm'
    | '/dashboard'
    | '/equipe'
    | '/legal-cases'
    | '/plans'
    | '/telefonia'
    | '/api/public/webhooks/uazapi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agentes'
    | '/_authenticated/chat'
    | '/_authenticated/comercial'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/criativos'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/legal-cases'
    | '/_authenticated/plans'
    | '/_authenticated/telefonia'
    | '/api/public/webhooks/uazapi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksUazapiRoute: typeof ApiPublicWebhooksUazapiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/telefonia': {
      id: '/_authenticated/telefonia'
      path: '/telefonia'
      fullPath: '/telefonia'
      preLoaderRoute: typeof AuthenticatedTelefoniaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal-cases': {
      id: '/_authenticated/legal-cases'
      path: '/legal-cases'
      fullPath: '/legal-cases'
      preLoaderRoute: typeof AuthenticatedLegalCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criativos': {
      id: '/_authenticated/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof AuthenticatedCriativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/uazapi': {
      id: '/api/public/webhooks/uazapi'
      path: '/api/public/webhooks/uazapi'
      fullPath: '/api/public/webhooks/uazapi'
      preLoaderRoute: typeof ApiPublicWebhooksUazapiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedCriativosRoute: typeof AuthenticatedCriativosRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedLegalCasesRoute: typeof AuthenticatedLegalCasesRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedTelefoniaRoute: typeof AuthenticatedTelefoniaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentesRoute: AuthenticatedAgentesRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedCriativosRoute: AuthenticatedCriativosRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedLegalCasesRoute: AuthenticatedLegalCasesRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedTelefoniaRoute: AuthenticatedTelefoniaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksUazapiRoute: ApiPublicWebhooksUazapiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
